### ISSUE TITLE
I have a question about downloading the dataset 

### ISSUE THREAD

**Issue by whoamibro** [lemondan/HumanParsing-Dataset#14]
I tried to download the data, but there's no ID information. And also the link you share is expired I think. Could you tell us more specific explanation of the way to download the dataset?

**Comment by lemondan** [comment]
You can refer to this link: https://github.com/Engineering-Course/LIP_SSL

Best
Xiaodan

**Comment by whoamibro** [comment]
Thank you for fast and kind reply!!
